# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: CultureHQ/actions-yarn@v1.0.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: git config --global user.email "joey.comhaire@gmail.com"
      - run: git config --global user.name "Joey Comhaire"
      - run: yarn install
      - run: yarn test
      - run: yarn build
      - name: Deploy with gh-pages
        run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn deploy
